language: python

python:
  - "2.7"
  - "3.6"
  - "3.7-dev"

install:
  - python setup.py -q install
  - pip install -r requirements.txt
  - pip install pandas
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-mock

script:
  - pytest --cov

after_success:
  - coverage combine
  - codecov
