language: python

matrix:
    include:
        - python: 2.7
        - python: 3.6
        - python: 3.7-dev
    allow_failures:

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${TRAVIS_PYTHON_VERSION%-*}
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  - python setup.py -q install
  - pip install -r requirements/test.txt

script:
  - pytest --cov

after_success:
  - coverage combine
  - codecov

cache: apt

deploy:
  provider: pypi
  user: tai.sakuma
  distributions: sdist bdist_wheel --universal
  password:
    secure: Ms4tG270iJCDmnufjFohNyO3gNMetDOabps08nV2By89q8nqwVsSZdTO38JE5RvCtLDiIei/qc14hZ75rf0MGK04jRBc4ApMusvzpZYHoLUp5LDaangYQzvDSlY82pwi12GRnLF4a1CpuoNQ0nvvqNL6r4++q+racFDmpgfdLgRqAXi7HiMnYe8xcfyZnpD6QM76n+MINzHQQ3IrhUIHn4kiN708BdwpZqw1/+uFIT+Pst0RHwHU0tMzch9r1iT/q/qdgAP0WJMwgQCo5dVD2yA8BzNKrzv9lqIoGvEUpQmKm8XoOtrQxO7oMGJPCaXJ/7jplK7mB3RrxPy/j0s50K8WyAsf2d/L8TJtFz+I8vqN7ZN2tVXy22txedziOxggnLyouyL2Jn6nELBv7qdSjXYoLT9GIx3NYvHJ9HSw/W3XapUDEvSMwuicsm5WjbH5+xnnWfottW6CXpV62xL2fZNVJxyTfFt8X1a2MbMGbTBLcqBJnnQrMpQXe6rhBy0cQR/4kZmitpcIl6s+82axbWiwwR9XxiRelWftcGFgk7XC5OG6ZgQutUHv73XHNssDBeoVdAGgvl14LVtGq/V7QM7SN7k7HUegL2W0RVn6t8RYrENbkgPeBxl1e4GHqyrXCbD+np61+PjxxcW2Dcn9iuXRTesuN1q2y3BRJAZm2XY=
  on:
    tags: true
    python: 3.6
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
